site_name: Aliyun 计算巢 x Agent Manager
theme: 
  name: aliyuncomputenest
nav:
  - Demo服务实例部署文档: index.md
  - Release Notes:
    - 概览: release-notes/README.md
    - v1.0.6: release-notes/v1.0.6.md
    - v1.0.5: release-notes/v1.0.5.md
    - v1.0.4: release-notes/v1.0.4.md
    - v1.0.3: release-notes/v1.0.3.md
    - v1.0.2: release-notes/v1.0.2.md
    - v1.0.1: release-notes/v1.0.1.md
    - v1.0.0: release-notes/v1.0.0.md