apiVersion: agents.kruise.io/v1alpha1
kind: SandboxSet
metadata:
  name: hermes
  namespace: default
spec:
  persistentContents:
    - filesystem
  replicas: 1
  runtimes:
    - name: agent-runtime
  template:
    metadata:
      labels:
        app: hermes
        alibabacloud.com/acs: "true"
      annotations:
        image.alibabacloud.com/enable-image-cache: "true"
        network.alibabacloud.com/network-policy-mode: "traffic-policy"
        network.alibabacloud.com/enable-network-policy-agent: "true"
    spec:
      automountServiceAccountToken: false
      containers:
        - command:
            - supervisord
            - '-n'
          env:
            - name: ENVD_DIR
              value: /mnt/envd
            - name: KUBERNETES_SERVICE_PORT_HTTPS
              value: ""
            - name: KUBERNETES_SERVICE_PORT
              value: ""
            - name: KUBERNETES_PORT_443_TCP
              value: ""
            - name: KUBERNETES_PORT_443_TCP_PROTO
              value: ""
            - name: KUBERNETES_PORT_443_TCP_ADDR
              value: ""
            - name: KUBERNETES_SERVICE_HOST
              value: ""
            - name: KUBERNETES_PORT
              value: ""
            - name: KUBERNETES_PORT_443_TCP_PORT
          image: >-
            compute-nest-registry.cn-hangzhou.cr.aliyuncs.com/computenest/aliyun-computenest/openclaw-manager-hermes-test:v0.0.1
          imagePullPolicy: IfNotPresent
          name: hermes
          ports:
            - containerPort: 8080
              name: hermes
              protocol: TCP
            - containerPort: 9119
              name: dashboard
              protocol: TCP
            - containerPort: 49983
              name: runtime
              protocol: TCP
          resources:
            limits:
              cpu: '2'
              memory: 4Gi
            requests:
              cpu: '2'
              memory: 4Gi
          securityContext:
            readOnlyRootFilesystem: false
            runAsGroup: 0
            runAsUser: 0
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /root/.hermes
              name: hermes-data
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      hostname: hermes
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: { }
          name: hermes-data