[program:hermes]
command=/opt/hermes/docker/entrypoint.sh gateway run
user=root
environment=HOME="/root"
redirect_stderr=true
stdout_logfile=/proc/1/fd/1
stdout_logfile_maxbytes=0
autorestart=true
startretries=-1
stopasgroup=true
killasgroup=true318513gh
